# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Loginvalid' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'loginvalid' do
    @driver.get('http://the-internet.herokuapp.com/login')
    @driver.manage.resize_to(697, 728)
    @driver.find_element(:id, 'username').click
    @driver.find_element(:id, 'username').send_keys('tomsmith')
    @driver.find_element(:css, '.subheader').click
    @driver.find_element(:id, 'password').click
    @driver.find_element(:id, 'password').send_keys('SuperSecretPassword!')
    @driver.find_element(:css, '.fa').click
  end
end
